---
title: Bayesian Estimation from Bernoulli Distribution
author: Akihiko Mori
date: '2022-05-16'
slug: []
categories: []
tags: 
- Bayes Statistics
---

## Purpose

## TOC
1. Library
2. True Distribution
3. Prior Distribution
4. Data
5. Post Distribution

## Library
```{r}
library(ggplot2)
set.seed(1)
```

## True Distribution
```{r}
x <- 0:1
p <- 0.8
prob <- dbinom(x, 1, p)

ggplot() + 
  geom_bar(aes(x, prob), stat ="identity") +
  labs(x="x", y="prob", title="Bernoulli Distribution")+
  theme_classic(base_family = "") +
  theme(text = element_text(size = 20))+
  ggeasy::easy_center_title()
```


## Prior Distribution
```{r}
a_pre <- 2
b_pre <- 2
x <- seq(0,1, 0.01)
p_prob_pre <- dbeta(x, a_pre, b_pre)

plot <- ggplot()+
  geom_line(aes(x=x, y=p_prob_pre))+
  labs(x="p", y="prob", title="Beta Distribution")+
  theme_classic(base_family = "") +
  theme(text = element_text(size = 20))+
  ggeasy::easy_center_title()
plot
```

## Data
```{r}
data <- rbinom(30, 1, p)
N <- length(data)
```

## Post Distribution
```{r}
a_pos <- sum(data) + a_pre
b_pos <- N - sum(data) + b_pre
x <- seq(0,1, 0.01)
p_prob_pos <- dbeta(x, a_pos, b_pos)

plot + geom_line(aes(x=x, y=p_prob_pos), col="blue")
```

