---
title: Cluster Analysis (Hierarchical Clustering)
author: Akihiko Mori
date: '2022-06-24'
slug: []
categories: []
tags:
  - Multivariate Analysis
---

## Purpose
A cluster analysis (Hierarchical Clustering) with Ward's method will be implemented using R. 
The data is implemented randomly, 
so it can be reproduced by copy and paste.

## TOC
1. Library
2. Data Generation
3. Data Visualization
4. Analysis
5. Results of Analysis

## Library
```{r message=FALSE}
library(dplyr)
library(ggplot2)
```

## Data Generation
```{r, message=FALSE}
set.seed(1)
engl <- c(rnorm(5, 50, 10), rnorm(5, 70, 10))%>% round()
math <- c(rnorm(5, 50, 10), rnorm(5, 30, 10))%>% round()
data <- data.frame(engl, math)
data %>% head()
```


## Data Visualization
```{r, message=FALSE}
data %>%
  ggplot()+
  geom_point(aes(engl, math)) +
  theme_classic(base_family = "HiraKakuPro-W3")+
  theme(text=element_text(size=30))+
  labs(title="Scatter Plot")
```


## Cluster Analysis
```{r}
D <- dist(data, method = "euclidean")
cls <- hclust(D, method = "ward.D")
plot(as.dendrogram(cls))
```

## Results of Analysis
```{r}
a0 <- - apply(model$means %*% model$scaling,2,mean)
x <- seq(1400, 2200,1)
y <- -model$scaling[1]/model$scaling[2]*x - a0/model$scaling[2]
mu <- apply(model$means, 2, mean)
ggplot()+
geom_point(aes(data$sales, data$counts, col=customers))+
geom_point(aes(mu[1], mu[2]), size=3) +
theme_classic(base_family = "HiraKakuPro-W3")+
theme(text=element_text(size=30)) +
labs(title="Scatter Plot", x="Sales", y="Counts") +
geom_line(aes(x,y))
```