---
title: Multiple Regression Analysis
author: Akihiko Mori
date: '2022-06-22'
slug: []
categories: []
tags:
  - Multivariate Analysis
---

## Purpose
A multiple regression analysis will be implemented using R. 
The data will be implemented from the data generation, 
so it can be reproduced by copy and paste.

## TOC
1. Library
2. Data Generation
3. Analysis
4. Multicollinearity

## Library
```{r message=FALSE}
library(dplyr)
library(ggplot2)
```

## Data Generation
```{r, message=FALSE}
set.seed(10)
age   <- rnorm(100, 40, 20) 
width <- rnorm(100, 40, 3)
height<- rnorm(100, 170, 10)
err   <- rnorm(100, 0, 50) 
income <- 5*age + rnorm(100,10*width,70) + 300 + err
data <-data.frame(age, width, height, income) %>%
filter(18<age&age<60) %>%
mutate(age=round(age), income=round(income), height=round(height), width=round(width))
data %>% head()
```


## Results of Multilinear Regression Analysis
```{r}
model <- lm(data=data, income~age+width+height)
summary(model)
```

## Multicollinearity
```{r}
set.seed(1)
age <- rnorm(100, 40, 20) 
width <- rnorm(100, age, 1) 
height <- rnorm(100, 170, 10)
err <- rnorm(100, 0, 50) 
income <- 5*age + rnorm(100,10*width,70) + 300 + err
data <-data.frame(age, width, height, income) %>%
  filter(18<age&age<60) %>%
  mutate(age=round(age), income=round(income), height=round(height), width=round(width))
data %>% head()
cor(data[,c(4,1:3)])

model <- lm(data=data, income~age+width+height)
summary(model)
```